# docker-compose.yml

version: '3'
services:

  mssql-server-linux:
    image: microsoft/mssql-server-linux:latest
    container_name: sql_server
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P455w0rd
    ports:
      - "1433:1433"

volumes:
  mssql-server-linux-data:   
